---
title: "Simple R Markdown Notebook"
author: "Lincoln Mullen"
---

### What is this?

This is a 'fork' - a copy - of Lincoln Mullen's 'Simple R Markdown Notebook'. [R Markdown](http://rmarkdown.rstudio.com/) is like 'ordinary' Markdown with the added benefit of being able to run and display R code you use for your analysis. In this version of Mullen's notebook, we've added code to support the [hypothes.is](http://hypothes.is) web annotation framework. That way, not only can you share your notes, your code, and your results, but others can annotate and share their annotations! 

For example, here is the table of contents for rendered versions of every R Markdown document in this repository.

### Table of contents

```{r echo=FALSE, results='asis', warning=-1}
rmd <- Sys.glob("*.Rmd")
rmd <- rmd[rmd != "index.Rmd"]
html <- sub(".Rmd", ".html", rmd)
lines <- lapply(rmd, readLines)
yaml <- lapply(lines, rmarkdown:::parse_yaml_front_matter)
cat("<ul>")
for (i in seq_along(rmd)) {
  cat(paste0("<li><a href='", html[i], "'>", yaml[[i]]$title, "</a><br/>",
             "<code>", rmd[i], "</code>", "</li>"))
}
cat("</ul>")
```

### What does this do?

As little as possible. The aim is to be very lightweight. But it does do this:

1. Includes an index page (you're looking at it) with a table of contents for every `.Rmd` file in the root directory of your project.
2. Inserts a navigation header into each rendered HTML file.
4. Sets some shared options for HTML documents rendered from R Markdown.
5. Contains a basic Makefile to render all the documents.
  
If you want to get fancy, you can add these two lines to the `[remote "origin"]` section of your `.git/config` file, so that any `git push` command will push to both the `master` and the `gh-pages` branch. Or you can just rename `master` to `gh-pages`. (This tip from [Brett Terpstra](http://brettterpstra.com/2012/09/26/github-tip-easily-sync-your-master-to-github-pages/), who gives more details.)

```
push = +refs/heads/master:refs/heads/gh-pages
push = +refs/heads/master:refs/heads/master
```

Don't forget to commit the HTML files that you generate.

See the [GitHub repository](https://github.com/lmullen/rmd-notebook) for the source. See the [R Markdown documentation](http://rmarkdown.rstudio.com/) if you want to do more.

### So, what do I do again?

1. While logged in to your Github account, clone (copy) this repo to your own account.
2. Make a gh-pages branch. Set that branch as the default branch via the settings.
2. Clone your version of the notebook to your machine.

Within R Studio or from the command line (within the notebook folder) or from your favourite text editor:

+ Write your code or your notes in a text file. Make sure that the start of your file has the metadata describing it between three dashes, 
```
---
title: "First page of the notebook"
author: "Your Name"
date: "December 3, 2015"
---
```

and save them with the .Rmd file extension. Use numbers at the start of the file name, eg `01-my-first-note.Rmd`, `02-thoughts-on-Laurence-1999.Rmd`. Make sure you're saving within the notebook folder.

+ From the command line, type `make`
+ Add your changes to git.
+ Make a commit.
+ Push your changes to your gh-pages branch of your notebook.

Your notebook now lives at the <your-account-name>.github.io/<path-to-your-notebook>
